### ISSUE TITLE
How to run this program

### ISSUE THREAD

**Issue by RSKRAO** [yassersouri/simple-augmented-reality#1]
![test3](https://user-images.githubusercontent.com/35143783/36521539-28ad2f00-17bd-11e8-9ce5-8cbde776e2f7.jpg)
I have a solar panel image and I need to detect the squares with Blue and lite blue colors and return the count of both separately. Could you guide me in this.

**Comment by yassersouri** [comment]
Sorry, this is not related to this repository.
